
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Coach_Degree
    {
        public decimal iD_Coach { get; set; }
        public decimal iD_Degree { get; set; }
        public System.DateTime dateReceived { get; set; }
        public string university { get; set; }

        public virtual Coach Coach { get; set; }
        public virtual Degree Degree { get; set; }
    }
}
