
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coach()
        {
            this.Coach_Degree = new HashSet<Coach_Degree>();
            this.Coach_Direction = new HashSet<Coach_Direction>();
            this.Coach_Email = new HashSet<Coach_Email>();
            this.Coach_Phone = new HashSet<Coach_Phone>();
            this.Coach_Team = new HashSet<Coach_Team>();
        }

        [Display(Name = "Identificador")] public decimal iD { get; set; }
        [Display(Name = "Nombre")] public string coach_Name { get; set; }
        public byte[] imageURL { get; set; }
        [Display(Name = "Fecha de nacimiento")][DataType(DataType.Date)] public System.DateTime birthdate { get; set; }
        [Display(Name = "Jugador en su juventud")] public string wasPlayer { get; set; }
        [Display(Name = "Fecha de inicio")][DataType(DataType.Date)] public System.DateTime dateStart { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach_Degree> Coach_Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach_Direction> Coach_Direction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach_Email> Coach_Email { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach_Phone> Coach_Phone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach_Team> Coach_Team { get; set; }
    }
}
