
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Coach_Team
    {
        public decimal team { get; set; }
        public decimal coach { get; set; }
        [Display(Name = "Fecha de firma")][DataType(DataType.Date)] public System.DateTime signDate { get; set; }
        [Display(Name = "Fecha de separacion")] [DataType(DataType.Date)] public System.DateTime expirationDate { get; set; }
        [Display(Name = "Fecha de separacion")] [DataType(DataType.Date)] public System.DateTime breakupDate { get; set; }
        [Display(Name = "Salario")] public decimal wage { get; set; }

        public virtual Coach Coach1 { get; set; }
        public virtual Team Team1 { get; set; }
    }
}
