
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Goal
{

        [Display(Name = "Partido")] public decimal match { get; set; }

        [Display(Name = "Jugador")] public decimal player { get; set; }

        [Display(Name = "Minuto")] public decimal minute { get; set; }

        [Display(Name = "Equipo")] public decimal team { get; set; }

        [Display(Name = "Tipo")] public string gType { get; set; }



    public virtual LineUp LineUp { get; set; }

    public virtual goalType goalType { get; set; }

}

}
