
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LineUp
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LineUp()
    {

        this.Goals = new HashSet<Goal>();

    }


        [Display(Name = "Jugador")] public decimal player { get; set; }

        [Display(Name = "Equipo")] public decimal match { get; set; }

        [Display(Name = "Minuto de ingreso")] public decimal minuteIn { get; set; }

        [Display(Name = "Fecha de salida")] public decimal minuteOut { get; set; }

        [Display(Name = "Posicion")] public string position { get; set; }

    public Nullable<decimal> team { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Goal> Goals { get; set; }

    public virtual Match Match1 { get; set; }

    public virtual Player Player1 { get; set; }

    public virtual PossiblePosition PossiblePosition { get; set; }

    public virtual Team Team1 { get; set; }

}

}
