
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.LineUps = new HashSet<LineUp>();
            this.Match_Referee = new HashSet<Match_Referee>();
        }

        public decimal id { get; set; }
        [Display(Name = "Casa")] public decimal home { get; set; }
        [Display(Name = "Visita")] public decimal away { get; set; }
        [Display(Name = "Goles de casa")] public short goalsHome { get; set; }
        [Display(Name = "Goles de Visita")] public Nullable<short> goalsAway { get; set; }
        [Display(Name = "Jornada")] public decimal matchday { get; set; }
        [Display(Name = "Temporada")] public short startYear { get; set; }
        [Display(Name = "Competencia")] public decimal competition { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineUp> LineUps { get; set; }
        public virtual Matchday Matchday1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Match_Referee> Match_Referee { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }

        public Match(int h, int a, short gH, short gA, int m, short sY, int c)
        {
            home = h;
            away = a;
            goalsHome = gH;
            goalsAway = gA;
            matchday = m;
            startYear = sY;
            competition = c;
        }
    }
}
