
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Player_Team
{

    public decimal player { get; set; }

    public decimal team { get; set; }

    public decimal wage { get; set; }

    [DataType(DataType.Date)] public System.DateTime signDate { get; set; }

    [Display(Name ="Fecha Expiración")] [DataType(DataType.Date)] public System.DateTime expirationDate { get; set; }

    [Display(Name = "Fecha Salida")] [DataType(DataType.Date)] public System.DateTime breakUpDate { get; set; }



    public virtual Player Player1 { get; set; }

    public virtual Team Team1 { get; set; }

}

}
