
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Referee
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Referee()
    {

        this.Match_Referee = new HashSet<Match_Referee>();

    }


    public decimal id { get; set; }

        [Display(Name = "Nombre del arbitro")] public string name { get; set; }

        [Display(Name = "Nacionalidad")] public string country { get; set; }



    public virtual Country Country1 { get; set; }

    public virtual Country Country2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Match_Referee> Match_Referee { get; set; }

}

}
