
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FootballManagerApp.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Season
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Season()
    {

        this.Matchdays = new HashSet<Matchday>();

    }


        [Display(Name = "Tempordad")] public short startYear { get; set; }

        [Display(Name = "Competencia")] public decimal competition { get; set; }

        [Display(Name = "Fecha de inicio")] [DataType(DataType.Date)] public System.DateTime beginDate { get; set; }

        [Display(Name = "Fecha final")] [DataType(DataType.Date)] public System.DateTime endDate { get; set; }



    public virtual Competition Competition1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Matchday> Matchdays { get; set; }

}

}
